### ISSUE TITLE
No postgis enabled?

### ISSUE THREAD

**Issue by Jyrks** [camptocamp/docker-postgres#10]
So I started the container:
docker run -d -it --name postgis -p 5432:5432 mdillon/postgis:9.6

Created a DB and tried to create a table:

CREATE TABLE mytable (
id SERIAL PRIMARY KEY,
geom GEOMETRY(Point, 26910),
name VARCHAR(128)
);

And got:

ERROR: type "geometry" does not exist
LINE 3: geom GEOMETRY(Point, 26910),
^

********** Error **********

ERROR: type "geometry" does not exist
SQL state: 42704
Character: 57

**Comment by fredj** [comment]
postgis is not enabled by default, you need to install it with:
```sql
CREATE EXTENSION postgis;
```

**Comment by Jyrks** [comment]
You're right. Thanks!
